### PR TITLE
Update Cargo.lock for 1.6.0

### PR DESCRIPTION
**Pull request by orhun**

### CODE REVIEW

**Comment by jplatte** [comment]
Hm, I haven't used CI publish workflows before and am a *little* wary about them.

Also I need to re-think how I handle this project overall, it's currently dual-hosted on git.sr.ht and GitHub and has no CI at all, which is also rather weird for accepting external contributions 😅

How about this: I want to try out codeberg.org's CI soon anyways, if I *don't* like it I'll create an initial GitHub Actions CI workflow myself for PRs, and then ping you about the release workflow.

**Comment by orhun** [comment]
Sounds good!

**Comment by jplatte** [comment]
Ah, well I didn't even make a PR at all when bumping the version, so there was no CI that would have been able to catch the error (prior to releasing). But I'll keep this in mind for future CI workflows to use `--locked` when there is a lockfile.

**Comment by orhun** [comment]
Great, applied some suggestions in #21

**Pull request merged**
